### ISSUE TITLE
Done and delete icon color issue

### ISSUE THREAD

**Issue by XxDextroxX** [JoshuaObateru/pin_plus_keyboard#1]
With the dark theme the done and delete buttons are not visible because their colors are set to black, please change to make it customizable.
With the dark theme the done and delete buttons are not visible because their colors are set to black, please change to make it customizable
![image](https://user-images.githubusercontent.com/62032726/167450224-0870b6f2-7b54-4f87-b7b5-a59a7a9e61a1.png)
![image](https://user-images.githubusercontent.com/62032726/167450245-98208bd8-08a5-4c89-8ffc-e53dd1e071b2.png)

**Comment by JoshuaObateru** [comment]
I've updated the package
version 0.0.9 fixes this issue. Please look at the version releases to find more details on version 0.09.

**Comment by XxDextroxX** [comment]
Hello, I just updated the package, thank you very much, it was very
helpful, I am a beginner in flutter, greetings
